spring.application.name=prometeus
server.port=3030

#Configuracion de BD
spring.datasource.url=jdbc:postgresql://localhost:5432/prometeus
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=uns20

#Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

<<<<<<< Updated upstream
# Logging
logging.level.com.prometeus=DEBUG
logging.level.org.springframework.web=DEBUG
=======
#Configuracion de Endpoint de la API de prediccion
# Declara la URL base (host y puerto)
service.api-prediction.base-url=http://localhost:8000
# Declara la ruta específica de prediccion
service.prediction.path=/predecir/
>>>>>>> Stashed changes
