spring.application.name=prometeus
server.port=3030

#Configuracion de BD
spring.datasource.url=jdbc:postgresql://localhost:5432/prometeus
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=uns20

#Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Configuracion de Endpoint de la API de prediccion
# Declara la URL base (host y puerto)
service.prediction.base-url=http://localhost:8000
# Declara la ruta específica de prediccion
service.prediction.path=/predecir/
#Declara el plazo entre autoentrenamientos
service.autoentrenamientos.path=/auto-entrenamiento/

spring.thymeleaf.cache=false