spring.application.name=prometeus
server.port=3030

#Configuracion de BD
spring.datasource.url=jdbc:postgresql://localhost:5432/prometeus
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=
spring.datasource.password=

#Configuracion de JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true